---
kind: pipeline
type: kubernetes
name: default

environment:
  GOCACHE: /cache/pkg/cache
  GOMODCACHE: /cache/pkg/mod

steps:
  - name: fetch-tags
    image: alpine/git
    commands:
      - git fetch --tags
    resources:
      requests:
        cpu: 250
        memory: 50MiB
      limits:
        cpu: 250
        memory: 100MiB

  - name: test
    image: golang:1.20.5
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    commands:
      - ./scripts/download-test-geoip
      - go get
      - go test -v ./...
      - go build ./...
    resources:
      requests:
        cpu: 1000
        memory: 128MiB
      limits:
        cpu: 2000
        memory: 2GiB

  - name: goreleaser
    image: golang:1.20.5
    resources:
      requests:
        cpu: 4000
        memory: 512MiB
      limits:
        cpu: 10000
        memory: 2048MiB
    volumes:
      - name: go
        path: /go
      - name: gopkg
        path: /cache
    commands:
      - go install github.com/goreleaser/goreleaser@v1.19.2
      - ./scripts/run-goreleaser
      - echo Done
    when:
      ref:
        - refs/heads/main
        - refs/heads/avro
        - refs/tags/**
    depends_on: [test]

  - name: upload
    image: plugins/s3
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    settings:
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      bucket: geodns
      target: /geodns/builds/test/${DRONE_BUILD_NUMBER}
      source: dist/*
      strip_prefix: dist/
      endpoint: https://minio-ewr1.develooper.com/
      path_style: true
    depends_on: [goreleaser]

  - name: fury-publish
    image: golang:1.20.5
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    environment:
      FURY_TOKEN:
        from_secret: fury_test_token
    commands:
      - ./scripts/fury-publish ntppool-test
    when:
      ref:
        - refs/heads/main
        - refs/heads/drone-test
        - refs/tags/**
    depends_on: [goreleaser]

volumes:
  - name: go
    temp: {}
  - name: gopkg
    claim:
      name: go-pkg

trigger:
  event:
    - push
    - tag
    - pull_request

---
kind: pipeline
type: kubernetes
name: publish-production

steps:
  - name: download
    image: golang:1.20.5
    commands:
      - ./scripts/download-release geodns test/${DRONE_BUILD_PARENT} dist/
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB

  - name: upload
    image: plugins/s3
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    settings:
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      bucket: geodns
      target: /geodns/builds/release/${DRONE_BUILD_NUMBER}
      source: dist/*
      strip_prefix: dist/
      endpoint: https://minio-ewr1.develooper.com/
      path_style: true
    depends_on: ["download"]

  - name: fury-publish
    image: golang:1.20.5
    resources:
      requests:
        cpu: 250
        memory: 64MiB
      limits:
        cpu: 250
        memory: 256MiB
    environment:
      FURY_TOKEN:
        from_secret: fury_token
    commands:
      - ./scripts/fury-publish ntppool
    depends_on: ["download"]

trigger:
  event:
    - promote
  target:
    - publish
---
kind: signature
hmac: ca3996a809efaa311bfdc783ed6453abdbd2bcd996947bf483ac0e9bbba512a1

...
